platform :ios, '10.0'
use_frameworks!

target 'Stocks' do
	pod 'SVProgressHUD'
    pod 'SBPickerSelector'
    pod 'DateTools'
	pod 'RealmSwift'
	pod 'Alamofire'
	pod 'AlamofireImage'
	pod 'ObjectMapper'
    pod 'RealReachability'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxRealm'
    pod 'AlamofireObjectMapper'
    
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3'
    end
  end
end
